services:
  ui:
    build:
      context: .
      dockerfile: ./docker/production/node/Dockerfile
    image: 'interface_node'
    container_name: 'interface_node'
    env_file:
      - ./env/public
      - ./env/secret
    ports:
      - '8080:8080'
